---

- name: Maintenance
  hosts: all
  remote_user: root
  gather_facts: no
  tasks:
    - name: Cleanup all exited docker containers
      command: "docker system prune -a -f"

    - name: Delete all docker images
      command: "docker image prune -a -f"

