---

- name: Maintenance
  hosts: all
  remote_user: root
  tasks:
    - name: Upgrade the atomic host platform to the latest version (atomic host upgrade)
      atomic_host:
        revision: latest

